#include <cstdlib>    // for std::system
#include <iostream>   // for std::cout, std::cerr
#include <fstream>    // for std::ifstream
#include <string>     // for std::string
#include <vector>     // for std::vector

int main() {
    // Number of data points
    int n_of_bs = 100;

    // Build the command string
    std::string command = "./dist/main/nuclear_helper plot=True n_of_bs=" + std::to_string(n_of_bs);

    // Run the external command
    int result = std::system(command.c_str());
    std::cout << "Process exited with code: " << result << std::endl;

    // Now load the data from the file generated by nuclear_helper
    std::ifstream infile("data/density.txt");
    if (!infile) {
        std::cerr << "Error: Could not open density.txt" << std::endl;
        return 1;
    }

    // Create a 2D vector to hold the density data
    // Dimensions: n_of_bs x n_of_bs
    std::vector<std::vector<float> > density(n_of_bs, std::vector<float>(n_of_bs, 0.0f));

    // Read the data line-by-line
    for (int i = 0; i < n_of_bs; ++i) {
        for (int j = 0; j < n_of_bs; ++j) {
            double val;
            if (!(infile >> val)) {
                std::cerr << "Error reading data at line " << i << ", element " << j << std::endl;
                return 1;
            }
            density[i][j] = val;
        }
    }

    infile.close();


    // Print the data to the console for verification
    for (int i = 0; i < n_of_bs; ++i) {
        for (int j = 0; j < n_of_bs; ++j) {
            std::cout << density[i][j] << " ";
        }
        std::cout << "\n";
    }

    return 0;
}
